name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: Git tag or commit
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Include steps to reproduce
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Node, Docker versions
